### ISSUE TITLE
[UI Web] UHE ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by gramscih** [DMGochoa/final_prog102#19]
I had the following exception trying to execute UI Web, I reinstalled all packages from requirements.txt from the root folder

`Traceback (most recent call last):
  File "/home/ghermozo/Documents/proj102/final_prog102/UI_web/main.py", line 7, in <module>
    from auth import authenticate_user, validate_login_session
  File "/home/ghermozo/Documents/proj102/final_prog102/UI_web/auth.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
`

**Comment by DMGochoa** [comment]
In the new PR the requirements.txt has the _requests_ module specified. (Now is fixed)
